services:

  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
  
  laravel-docker-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
